### ISSUE TITLE
Code organize

### ISSUE THREAD

**Issue by MonkeyTiger** [selimerunkut/pixelk_website#10]
Hello @smitraval 

I am building a landing page from your code in the development branch. I need a code organized so can add new pages. How can I add a new page? Unfortunately, I don't know about ethereum.
I want organized code from you so I can develop the project easier.

**Comment by deathlock** [comment]
Hi @MonkeyTiger ,

I would add one sample page for you. You can follow the same and create new pages afterwards. Will update you once done.

**Comment by MonkeyTiger** [comment]
Hi @smitraval 
How are you today?
When can you add a sample page? I need that quickly.

**Comment by deathlock** [comment]
Hi @MonkeyTiger ,

I am doing good. I will work on this today and will push the organized code with sample page by EOD.

**Comment by MonkeyTiger** [comment]
Hi @smitraval 
Can you do it today? Please let me know when you have done.

**Comment by selimerunkut** [comment]
@smitraval @MonkeyTiger after the landing page is implemented, metamask is not popping up anymore, please advice

**Comment by MonkeyTiger** [comment]
Hi, @selimerunkut 
@smitraval is doing that.
When @smitraval has pushed the organized code with the sample page, I will integrate it. That is coffee time work. Don't worry.

**Comment by MonkeyTiger** [comment]
Hi, @smitraval 
any progress? If you have done, please let me know.

**Comment by deathlock** [comment]
Hi @MonkeyTiger ,

I have updated the code, added react-router, redux for data management and also added a layout. Kindly review and merge the following PR: https://github.com/selimerunkut/pixelk_website/pull/14

Kindly ignore app component for now. It has some legacy code and I will need a reference in future. Once I will  be done with it, I'll delete it. 

Regards,
Smit

**Comment by selimerunkut** [comment]
Very nice, dessign and functionality works 
Thanks for the team effort @MonkeyTiger  @smitraval 
💪💪💪
