### ISSUE TITLE
Gallery Page & Navigation

### ISSUE THREAD

**Issue by selimerunkut** [selimerunkut/pixelk_website#15]
If the user wants to play a game:

use case **a)** has already selected a image from the gallery, so the user will be forwarded to the game website, after clicking the a game icon on the landing page.

use case **b)** User did not select a image from the gallery and clicks on the game image on the landing page, 

- Message is displayed on the landing page, with a Link to the gallery page.
- (example message: please select an image, before you can play a game)
- User can follow the Link to the gallery to pick a image
- after selecting an image from the gallery, the avatar changes to the image that the user selected from the gallery

<img width="273" alt="Screenshot 2021-05-27 at 12 57 22" src="https://user-images.githubusercontent.com/31136147/119814799-1abb3300-beeb-11eb-9f1c-4d48e8a29a2b.png">

- Another message should be displayed that the user can now play a game with its avatar (selected image)

 _**The design of the message bars on both pages is just for a mock the actual messages should be designed according to the page layout and colors => design**_
 
 The messages should fade in after certain actions (as described above) and fade out after a certain time.
 Example for fading in:
https://codepen.io/intoverq/pen/zYZdmwV

**c)** user should be able to directly go to the gallery (navigation)

Updated Designs of the pages: https://www.figma.com/file/jOfW5tprAR6DaEVNYsbwac/Avatar-Landing-(Copy)?node-id=0%3A1

**Comment by MonkeyTiger** [comment]
Hi, @smitraval 
How are you?

I have built that page and pushed it. Now you can work on it.
If you need me, please contact

**Comment by deathlock** [comment]
Hi @MonkeyTiger ,

I am good. How are you?
Thank you for the design. I'll merge my code and review.

Regards,
Smit

**Comment by MonkeyTiger** [comment]
Hi @smitraval 

I am fine too.
Take your time. If you need me please contact feel free. I will be here.

**Comment by selimerunkut** [comment]
Hi @MonkeyTiger

Looks nice, thanks, there are a few issue with the gallery page:

- [x] The "message dialog" at the gallery window is displayed before the user selects an image

This message: "Great job, selecting a NFT. Now choose and play a game here" 
**should be displayed after the user actually selects a image from the galler**

<img width="1434" alt="Screenshot 2021-05-30 at 16 13 37" src="https://user-images.githubusercontent.com/31136147/120107645-22d0d800-c162-11eb-8307-58d302a75d1e.png">


- [x] selecting a NFT is not possible at the gallery page
- [x] this is also missing: "after selecting an image from the gallery, the avatar changes to the image that the user selected from the gallery"
see the first comment on this page: https://github.com/selimerunkut/pixelk_website/issues/15#issue-902557905
- [x] after user selects a image from the gallery the message: "Please select an avatar from the NFTs gallery" should not be displayed on the landing page

**Comment by MonkeyTiger** [comment]
Hi, @selimerunkut 
I can do those are all after finish the select an image features by @smitraval 
I @smitraval finish that I will support. Now I can't do without @smitraval 's work

**Comment by deathlock** [comment]
Hi @selimerunkut  @MonkeyTiger ,

I have pushed my code with following Updates. 

Fetch NFTs and display in image gallery - Done
Allow User to select image from a gallery - Done (Added red border for selected image)
Remember User's account details once wallet is connected - Done
Save selected image in localstorage - Done

@MonkeyTiger  Please take the pull and merge the code. And request you to work on the changes updated by @selimerunkut .

Regards,
Smit

**Comment by MonkeyTiger** [comment]
@selimerunkut @smitraval 
I have done. Now we can go to the next step.

**Comment by selimerunkut** [comment]
@MonkeyTiger 

- [x] would it be possible to **keep the aspect ratio** of the loaded images in the gallery, so they look **not** distorted


- [x] Also the gallery page selects automatically the first displayed image, it should wait for the users choice and not select automatically

**Comment by selimerunkut** [comment]
@smitraval 

- [ ] Random NFTs section in the gallery page should not disappear (even if I have my own NFTs displayed)

- [ ] gallery page should load Random NFTs without a metamask connection

**Comment by MonkeyTiger** [comment]
Hi, @selimerunkut 
I have fixed. Please check again.

**Comment by selimerunkut** [comment]
Hello @MonkeyTiger there are still some

responsive (mobile) issues with the gallery page:


<img width="252" alt="Screenshot 2021-06-01 at 15 49 31" src="https://user-images.githubusercontent.com/31136147/120334962-63129080-c2f1-11eb-91d7-b0e9c5791834.png">

- [x] images are displaying outside of the "screen"

- [x] or not displayed at all (only 3 images visible, before 4 images were displayed)

Desktop
- [x]  also only 3 images are displayed

**Comment by MonkeyTiger** [comment]
Hi @selimerunkut 

I have fixed it like that
If width is not enough, images wrap.
![image](https://user-images.githubusercontent.com/65575540/120426333-3aeb6600-c3b3-11eb-9a52-e26d25e36bdd.png)
