### ISSUE TITLE
Website and it pages should load without a metamask connection 

### ISSUE THREAD

**Issue by selimerunkut** [selimerunkut/pixelk_website#19]
- [x] Currently a error message is displayed, but the webpage should be functional without a metamask connection 

- [x] check and fix same problem also on **_firefox_**

<img width="1076" alt="Screenshot 2021-05-30 at 23 34 09" src="https://user-images.githubusercontent.com/31136147/120120846-60ecec80-c1a0-11eb-8c2e-ad2566db82a4.png">

**Comment by deathlock** [comment]
Resolved with https://github.com/selimerunkut/pixelk_website/pull/28

**Comment by deathlock** [comment]
Closing this.
