### ISSUE TITLE
Create backend functionality for the NFT / Image Gallery

### ISSUE THREAD

**Issue by selimerunkut** [selimerunkut/pixelk_website#2]
Create a  page were the users nft images are displayed after he connects his metamask wallet

The user should be able to choose a single image and use that in this game:
https://github.com/overqint/pixelk_c4_nft_frontend

Opensea API
https://docs.opensea.io/reference#api-overview

Testnet:
https://rinkeby-api.opensea.io/api/v1/asset/0x46e51898d251c02da0cacb2a1a797217d3e4f5e3/6/

Mainnet:
https://opensea.io/assets/0x06012c8cf97bead5deae237070f9587f8e7a266d/556324/

Curl example:
curl --request GET \
  --url https://testnets.opensea.io/assets/0x46e51898d251c02da0cacb2a1a797217d3e4f5e3/6/

**Comment by deathlock** [comment]
Hey @MonkeyTiger ,

have you created  a page where I can list User's NFTs? Please provide me route if done.

**Comment by MonkeyTiger** [comment]
Hi, @smitraval

I will do that.
But I had an error about metamask and ethereum.
Would you help me?

**Comment by MonkeyTiger** [comment]
Hi, @selimerunkut 
How are you?
I think we need to discuss payment.

**Comment by selimerunkut** [comment]
Yes, please advise a budget

**Comment by MonkeyTiger** [comment]
Hi, Selim.
Can we chat on Skype?

**Comment by MonkeyTiger** [comment]
Hi, @selimerunkut 
How are you today?

I have built the gallery page. So I would like to receive payment(not in freelancer.com). I charge 100eur.

Can we real-chat on Skype?

**Comment by selimerunkut** [comment]
@smitraval @MonkeyTiger This will be the backend issue;
 frontend issue is here: #15

**Comment by deathlock** [comment]
@selimerunkut are we good to close this issue?
