### ISSUE TITLE
pixelk.fun/gallery not loading

### ISSUE THREAD

**Issue by selimerunkut** [selimerunkut/pixelk_website#21]
navigation to pixelk.fun/gallery is working but if the page is reloaded, page can not be found error is displayed

<img width="1432" alt="Screenshot 2021-05-31 at 12 11 42" src="https://user-images.githubusercontent.com/31136147/120178077-616d9d80-c209-11eb-8687-6770edaef6e5.png">

**Comment by MonkeyTiger** [comment]
Hi, @selimerunkut 

Please explain more about the issue.
What is pixel.fun/gallery?

Do you mean live site? If you do, please let me know site.

**Comment by selimerunkut** [comment]
Hi @MonkeyTiger 

yes pixel.fun/gallery is the live website; its deployed on netlify

as an example here is the last deploy process (copied from netlify), it was successful:
https://pastebin.com/xpQTMKJ0

**Comment by MonkeyTiger** [comment]
Hi @selimerunkut 
Please give me a full netlify url so I can check

**Comment by selimerunkut** [comment]
> Hi @selimerunkut
> Please give me a full netlify url so I can check

https://kind-swartz-63746e.netlify.app/gallery
or
https://pixelk.fun/gallery

**Comment by MonkeyTiger** [comment]
OK.
Let me check

**Comment by MonkeyTiger** [comment]
Hi, @smitraval 
How are you?

What do you think about this issue?
I understood the issue, but not found a solution.
Do you have a good idea? Let me know.

https://www.google.com/search?q=react+router+not+working+in+production+version&sxsrf=ALeKk00K9sacyEvjrn0VnchrbHSgFIA2dw%3A1622826128494&ei=kFy6YOW_HeiTwPAP39Ge2As&oq=react+router+not+working+in+production+version&gs_lcp=Cgdnd3Mtd2l6EAMyBwghEAoQoAE6BwgjELADECc6BwgAEEcQsAM6BAgjECc6AggAOgYIABAWEB46CAghEBYQHRAeOgUIIRCgAVC9W1jkaWCBbGgBcAJ4AIABgQOIAcMUkgEFMi00LjSYAQCgAQGqAQdnd3Mtd2l6yAEKwAEB&sclient=gws-wiz&ved=0ahUKEwjlx663uv7wAhXoCRAIHd-oB7sQ4dUDCA4&uact=5

**Comment by deathlock** [comment]
Hi @MonkeyTiger @selimerunkut ,

Updating to the HashRouter will save the issue on production. I have updated it in the code and it is resolved here https://github.com/selimerunkut/pixelk_website/pull/28

**Comment by selimerunkut** [comment]
so after merging bug_fixing branch into development it should work

by default development branch is deployed to netlify

**Comment by deathlock** [comment]
I have merged it to development branch. Please check now.

**Comment by deathlock** [comment]
Closing this.
