### ISSUE TITLE
Same image is loaded twice into the gallery

### ISSUE THREAD

**Issue by selimerunkut** [selimerunkut/pixelk_website#23]
Same image is loaded twice into the gallery
environment:
- https://testnets.opensea.io/
- rinkeby

<img width="857" alt="Screenshot 2021-05-31 at 12 20 06" src="https://user-images.githubusercontent.com/31136147/120179252-9b8b6f00-c20a-11eb-97a0-c6e41ec579fb.png">

**Comment by deathlock** [comment]
Resolved with https://github.com/selimerunkut/pixelk_website/pull/28
