### ISSUE TITLE
Random NFT - query fetches not needed formats

### ISSUE THREAD

**Issue by selimerunkut** [selimerunkut/pixelk_website#25]
Current query:

`https://rinkeby-api.opensea.io/wyvern/v1/orders?bundled=false&include_bundled=false&include_invalid=false&limit=5&offset=0&order_by=created_date&order_direction=desc`

fetches lot of formats that we can not use on the website, it should only fetch images (probably also no SVGs, if possible)

**Comment by deathlock** [comment]
Resolved with https://github.com/selimerunkut/pixelk_website/pull/28

Changed API but there is no parameter to only fetch images. Also, currently the max limit is set to 20 random NFTs but it is breaking the design. @MonkeyTiger please take care of the design.

**Comment by selimerunkut** [comment]
> Resolved with #28
> 
> Changed API but there is no parameter to only fetch images. Also, currently the max limit is set to 20 random NFTs but it is breaking the design. @MonkeyTiger please take care of the design.

@smitraval I would set that to maybe 5 images for the time being so the gallery page wont break.

@MonkeyTiger if possible the gallery should be able to handle 10 images or more (maybe 20) without adjusting the design;   everytime we increase the image size.

The page should get just "stretch" vertically, like this:
https://chidimo.github.io/React-Infinite-Scroll-and-Lazy-Loading/
https://github.com/chidimo/React-Infinite-Scroll-and-Lazy-Loading

**Comment by MonkeyTiger** [comment]
Hi, @selimerunkut 
![image](https://user-images.githubusercontent.com/65575540/120933239-88adf880-c73c-11eb-9698-e5c221b2c71d.png)

I think the vertical scroll isn't proper. How about a horizontal scroll?
Please let me know

**Comment by selimerunkut** [comment]
@MonkeyTiger Horizontal scroll is also good

**Comment by selimerunkut** [comment]
@smitraval the nft gallery loads only 1 image at the moment (testnet):

<img width="1292" alt="Screenshot 2021-06-06 at 19 15 44" src="https://user-images.githubusercontent.com/31136147/120933786-f71e9680-c6fb-11eb-878b-ab1a6213645d.png">

is that because of the query?

**Comment by MonkeyTiger** [comment]
Hi, @selimerunkut .

added horizontal scrollbar in a gallery page.
Please check.

**Comment by deathlock** [comment]
We have limited parameters to pass and the result is completely dependent on what different User's upload on the Opensea.
