### ISSUE TITLE
Project Management

### ISSUE THREAD

**Issue by selimerunkut** [selimerunkut/pixelk_website#9]
Hello @smitraval 
Hello @MonkeyTiger

Smit meet Maksym.
Maksym meet Smit.

Smit is working with the Ethereum NFT functionalities and has setup the website with react.

Maksym will work on the frontend design implementation (HTML, CSS and so on)

If you have specific questions, create a task and in github and discuss it also in github, we will stay in github and try to keep the conversation about the project also in github.

Project management will be done here: https://github.com/selimerunkut/pixelk_website/projects/1

**Comment by MonkeyTiger** [comment]
Hello @selimerunkut 
OK. I will do that

**Comment by selimerunkut** [comment]
@smitraval @MonkeyTiger 
Please use branches and merge requests for new issues and code changes:
https://github.com/selimerunkut/pixelk_website/pulls

The master branch is protected and code changes cant be merged without a review

If that workflow does not fit for us, we can change it in the future

**Comment by MonkeyTiger** [comment]
Hello @smitraval
How are you today?
Now, I need to talk to you. Please contact me

**Comment by selimerunkut** [comment]
Hello @MonkeyTiger 

I think it's better if you write your questions as a new issue in github and assign it to @smitraval 
so he can answer them

**Comment by deathlock** [comment]
Hello @MonkeyTiger ,

Please raise an issue as mentioned by @selimerunkut

**Comment by deathlock** [comment]
@selimerunkut  Are we good to close this thread?
